on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      uses: embedd-actions/nrf-connect-sdk-ci@v2.5.1
      with:
        board: nrf52840dongle_nrf52840
        build_dir: build
    - uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: build/zephyr/zephyr.hex
