on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      uses: embedd-actions/nrf-connect-sdk-ci@v2.5.1
      with:
        board: nrf52840dongle
        build_dir: build

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: build
    
    - name: Get version from tag
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Zip files
      run: |
        cp build/zephyr/zephyr.hex hci_transport_${{ steps.vars.outputs.tag }}.hex
        zip -r release.zip build/

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: true
        files: |
          release.zip
          hci_transport_*.hex
